// Package schemas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package schemas

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ExtentSpatialCrs.
const (
	HttpwwwOpengisNetdefcrsOGC13CRS84 ExtentSpatialCrs = "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
)

// Valid indicates whether the value is a known member of the ExtentSpatialCrs enum.
func (e ExtentSpatialCrs) Valid() bool {
	switch e {
	case HttpwwwOpengisNetdefcrsOGC13CRS84:
		return true
	default:
		return false
	}
}

// Defines values for ExtentTemporalTrs.
const (
	HttpwwwOpengisNetdefuomISO86010Gregorian ExtentTemporalTrs = "http://www.opengis.net/def/uom/ISO-8601/0/Gregorian"
)

// Valid indicates whether the value is a known member of the ExtentTemporalTrs enum.
func (e ExtentTemporalTrs) Valid() bool {
	switch e {
	case HttpwwwOpengisNetdefuomISO86010Gregorian:
		return true
	default:
		return false
	}
}

// Defines values for FeatureCollectionGeoJSONType.
const (
	FeatureCollection FeatureCollectionGeoJSONType = "FeatureCollection"
)

// Valid indicates whether the value is a known member of the FeatureCollectionGeoJSONType enum.
func (e FeatureCollectionGeoJSONType) Valid() bool {
	switch e {
	case FeatureCollection:
		return true
	default:
		return false
	}
}

// Defines values for FeatureGeoJSONType.
const (
	FeatureGeoJSONTypeFeature FeatureGeoJSONType = "Feature"
)

// Valid indicates whether the value is a known member of the FeatureGeoJSONType enum.
func (e FeatureGeoJSONType) Valid() bool {
	switch e {
	case FeatureGeoJSONTypeFeature:
		return true
	default:
		return false
	}
}

// Defines values for GeometrycollectionGeoJSONType.
const (
	GeometryCollection GeometrycollectionGeoJSONType = "GeometryCollection"
)

// Valid indicates whether the value is a known member of the GeometrycollectionGeoJSONType enum.
func (e GeometrycollectionGeoJSONType) Valid() bool {
	switch e {
	case GeometryCollection:
		return true
	default:
		return false
	}
}

// Defines values for LinestringGeoJSONType.
const (
	LineString LinestringGeoJSONType = "LineString"
)

// Valid indicates whether the value is a known member of the LinestringGeoJSONType enum.
func (e LinestringGeoJSONType) Valid() bool {
	switch e {
	case LineString:
		return true
	default:
		return false
	}
}

// Defines values for MultilinestringGeoJSONType.
const (
	MultiLineString MultilinestringGeoJSONType = "MultiLineString"
)

// Valid indicates whether the value is a known member of the MultilinestringGeoJSONType enum.
func (e MultilinestringGeoJSONType) Valid() bool {
	switch e {
	case MultiLineString:
		return true
	default:
		return false
	}
}

// Defines values for MultipointGeoJSONType.
const (
	MultiPoint MultipointGeoJSONType = "MultiPoint"
)

// Valid indicates whether the value is a known member of the MultipointGeoJSONType enum.
func (e MultipointGeoJSONType) Valid() bool {
	switch e {
	case MultiPoint:
		return true
	default:
		return false
	}
}

// Defines values for MultipolygonGeoJSONType.
const (
	MultiPolygon MultipolygonGeoJSONType = "MultiPolygon"
)

// Valid indicates whether the value is a known member of the MultipolygonGeoJSONType enum.
func (e MultipolygonGeoJSONType) Valid() bool {
	switch e {
	case MultiPolygon:
		return true
	default:
		return false
	}
}

// Defines values for PointGeoJSONType.
const (
	Point PointGeoJSONType = "Point"
)

// Valid indicates whether the value is a known member of the PointGeoJSONType enum.
func (e PointGeoJSONType) Valid() bool {
	switch e {
	case Point:
		return true
	default:
		return false
	}
}

// Defines values for PolygonGeoJSONType.
const (
	Polygon PolygonGeoJSONType = "Polygon"
)

// Valid indicates whether the value is a known member of the PolygonGeoJSONType enum.
func (e PolygonGeoJSONType) Valid() bool {
	switch e {
	case Polygon:
		return true
	default:
		return false
	}
}

// Collection defines model for collection.
type Collection struct {
	// Crs the list of coordinate reference systems supported by the service
	Crs *[]string `json:"crs,omitempty"`

	// Description a description of the features in the collection
	Description *string `json:"description,omitempty"`

	// Extent The extent of the features in the collection. In the Core only spatial and temporal
	// extents are specified. Extensions may add additional members to represent other
	// extents, for example, thermal or pressure ranges.
	Extent *Extent `json:"extent,omitempty"`

	// Id identifier of the collection used, for example, in URIs
	Id string `json:"id"`

	// ItemType indicator about the type of the items in the collection (the default value is 'feature').
	ItemType *string `json:"itemType,omitempty"`
	Links    []Link  `json:"links"`

	// Title human readable title of the collection
	Title *string `json:"title,omitempty"`
}

// Collections defines model for collections.
type Collections struct {
	Collections []Collection `json:"collections"`
	Links       []Link       `json:"links"`
}

// ConfClasses defines model for confClasses.
type ConfClasses struct {
	ConformsTo []string `json:"conformsTo"`
}

// Exception Information about the exception: an error code plus an optional description.
type Exception struct {
	Code        string  `json:"code"`
	Description *string `json:"description,omitempty"`
}

// Extent The extent of the features in the collection. In the Core only spatial and temporal
// extents are specified. Extensions may add additional members to represent other
// extents, for example, thermal or pressure ranges.
type Extent struct {
	// Spatial The spatial extent of the features in the collection.
	Spatial *struct {
		// Bbox One or more bounding boxes that describe the spatial extent of the dataset.
		// In the Core only a single bounding box is supported. Extensions may support
		// additional areas. If multiple areas are provided, the union of the bounding
		// boxes describes the spatial extent.
		Bbox *[][]float32 `json:"bbox,omitempty"`

		// Crs Coordinate reference system of the coordinates in the spatial extent
		// (property `bbox`). The default reference system is WGS 84 longitude/latitude.
		// In the Core this is the only supported coordinate reference system.
		// Extensions may support additional coordinate reference systems and add
		// additional enum values.
		Crs *ExtentSpatialCrs `json:"crs,omitempty"`
	} `json:"spatial,omitempty"`

	// Temporal The temporal extent of the features in the collection.
	Temporal *struct {
		// Interval One or more time intervals that describe the temporal extent of the dataset.
		// The value `null` is supported and indicates an unbounded interval end.
		// In the Core only a single time interval is supported. Extensions may support
		// multiple intervals. If multiple intervals are provided, the union of the
		// intervals describes the temporal extent.
		Interval *[][]*time.Time `json:"interval,omitempty"`

		// Trs Coordinate reference system of the coordinates in the temporal extent
		// (property `interval`). The default reference system is the Gregorian calendar.
		// In the Core this is the only supported temporal coordinate reference system.
		// Extensions may support additional temporal coordinate reference systems and add
		// additional enum values.
		Trs *ExtentTemporalTrs `json:"trs,omitempty"`
	} `json:"temporal,omitempty"`
}

// ExtentSpatialCrs Coordinate reference system of the coordinates in the spatial extent
// (property `bbox`). The default reference system is WGS 84 longitude/latitude.
// In the Core this is the only supported coordinate reference system.
// Extensions may support additional coordinate reference systems and add
// additional enum values.
type ExtentSpatialCrs string

// ExtentTemporalTrs Coordinate reference system of the coordinates in the temporal extent
// (property `interval`). The default reference system is the Gregorian calendar.
// In the Core this is the only supported temporal coordinate reference system.
// Extensions may support additional temporal coordinate reference systems and add
// additional enum values.
type ExtentTemporalTrs string

// FeatureCollectionGeoJSON defines model for featureCollectionGeoJSON.
type FeatureCollectionGeoJSON struct {
	Features []FeatureGeoJSON `json:"features"`
	Links    *[]Link          `json:"links,omitempty"`

	// NumberMatched The number of features of the feature type that match the selection
	// parameters like `bbox`.
	NumberMatched *NumberMatched `json:"numberMatched,omitempty"`

	// NumberReturned The number of features in the feature collection.
	//
	// A server may omit this information in a response, if the information
	// about the number of features is not known or difficult to compute.
	//
	// If the value is provided, the value shall be identical to the number
	// of items in the "features" array.
	NumberReturned *NumberReturned `json:"numberReturned,omitempty"`

	// TimeStamp This property indicates the time and date when the response was generated.
	TimeStamp *TimeStamp                   `json:"timeStamp,omitempty"`
	Type      FeatureCollectionGeoJSONType `json:"type"`
}

// FeatureCollectionGeoJSONType defines model for FeatureCollectionGeoJSON.Type.
type FeatureCollectionGeoJSONType string

// FeatureGeoJSON defines model for featureGeoJSON.
type FeatureGeoJSON struct {
	Geometry   GeometryGeoJSON         `json:"geometry"`
	Id         *FeatureGeoJSON_Id      `json:"id,omitempty"`
	Links      *[]Link                 `json:"links,omitempty"`
	Properties *map[string]interface{} `json:"properties"`
	Type       FeatureGeoJSONType      `json:"type"`
}

// FeatureGeoJSONId0 defines model for .
type FeatureGeoJSONId0 = string

// FeatureGeoJSONId1 defines model for .
type FeatureGeoJSONId1 = int

// FeatureGeoJSON_Id defines model for FeatureGeoJSON.Id.
type FeatureGeoJSON_Id struct {
	union json.RawMessage
}

// FeatureGeoJSONType defines model for FeatureGeoJSON.Type.
type FeatureGeoJSONType string

// GeometryGeoJSON defines model for geometryGeoJSON.
type GeometryGeoJSON struct {
	union json.RawMessage
}

// GeometrycollectionGeoJSON defines model for geometrycollectionGeoJSON.
type GeometrycollectionGeoJSON struct {
	Geometries []GeometryGeoJSON             `json:"geometries"`
	Type       GeometrycollectionGeoJSONType `json:"type"`
}

// GeometrycollectionGeoJSONType defines model for GeometrycollectionGeoJSON.Type.
type GeometrycollectionGeoJSONType string

// LandingPage defines model for landingPage.
type LandingPage struct {
	Description *string `json:"description,omitempty"`
	Links       []Link  `json:"links"`
	Title       *string `json:"title,omitempty"`
}

// LinestringGeoJSON defines model for linestringGeoJSON.
type LinestringGeoJSON struct {
	Coordinates [][]float32           `json:"coordinates"`
	Type        LinestringGeoJSONType `json:"type"`
}

// LinestringGeoJSONType defines model for LinestringGeoJSON.Type.
type LinestringGeoJSONType string

// Link defines model for link.
type Link struct {
	Href     string  `json:"href"`
	Hreflang *string `json:"hreflang,omitempty"`
	Length   *int    `json:"length,omitempty"`
	Rel      *string `json:"rel,omitempty"`
	Title    *string `json:"title,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// MultilinestringGeoJSON defines model for multilinestringGeoJSON.
type MultilinestringGeoJSON struct {
	Coordinates [][][]float32              `json:"coordinates"`
	Type        MultilinestringGeoJSONType `json:"type"`
}

// MultilinestringGeoJSONType defines model for MultilinestringGeoJSON.Type.
type MultilinestringGeoJSONType string

// MultipointGeoJSON defines model for multipointGeoJSON.
type MultipointGeoJSON struct {
	Coordinates [][]float32           `json:"coordinates"`
	Type        MultipointGeoJSONType `json:"type"`
}

// MultipointGeoJSONType defines model for MultipointGeoJSON.Type.
type MultipointGeoJSONType string

// MultipolygonGeoJSON defines model for multipolygonGeoJSON.
type MultipolygonGeoJSON struct {
	Coordinates [][][][]float32         `json:"coordinates"`
	Type        MultipolygonGeoJSONType `json:"type"`
}

// MultipolygonGeoJSONType defines model for MultipolygonGeoJSON.Type.
type MultipolygonGeoJSONType string

// NumberMatched The number of features of the feature type that match the selection
// parameters like `bbox`.
type NumberMatched = int

// NumberReturned The number of features in the feature collection.
//
// A server may omit this information in a response, if the information
// about the number of features is not known or difficult to compute.
//
// If the value is provided, the value shall be identical to the number
// of items in the "features" array.
type NumberReturned = int

// PointGeoJSON defines model for pointGeoJSON.
type PointGeoJSON struct {
	Coordinates []float32        `json:"coordinates"`
	Type        PointGeoJSONType `json:"type"`
}

// PointGeoJSONType defines model for PointGeoJSON.Type.
type PointGeoJSONType string

// PolygonGeoJSON defines model for polygonGeoJSON.
type PolygonGeoJSON struct {
	Coordinates [][][]float32      `json:"coordinates"`
	Type        PolygonGeoJSONType `json:"type"`
}

// PolygonGeoJSONType defines model for PolygonGeoJSON.Type.
type PolygonGeoJSONType string

// TimeStamp This property indicates the time and date when the response was generated.
type TimeStamp = time.Time

// Bbox defines model for bbox.
type Bbox = []float32

// CollectionId defines model for collectionId.
type CollectionId = string

// Datetime defines model for datetime.
type Datetime = string

// FeatureId defines model for featureId.
type FeatureId = string

// Limit defines model for limit.
type Limit = int

// ConformanceDeclaration defines model for ConformanceDeclaration.
type ConformanceDeclaration = ConfClasses

// Feature defines model for Feature.
type Feature = FeatureGeoJSON

// Features defines model for Features.
type Features = FeatureCollectionGeoJSON

// InvalidParameter Information about the exception: an error code plus an optional description.
type InvalidParameter = Exception

// ServerError Information about the exception: an error code plus an optional description.
type ServerError = Exception

// AsFeatureGeoJSONId0 returns the union data inside the FeatureGeoJSON_Id as a FeatureGeoJSONId0
func (t FeatureGeoJSON_Id) AsFeatureGeoJSONId0() (FeatureGeoJSONId0, error) {
	var body FeatureGeoJSONId0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFeatureGeoJSONId0 overwrites any union data inside the FeatureGeoJSON_Id as the provided FeatureGeoJSONId0
func (t *FeatureGeoJSON_Id) FromFeatureGeoJSONId0(v FeatureGeoJSONId0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFeatureGeoJSONId0 performs a merge with any union data inside the FeatureGeoJSON_Id, using the provided FeatureGeoJSONId0
func (t *FeatureGeoJSON_Id) MergeFeatureGeoJSONId0(v FeatureGeoJSONId0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFeatureGeoJSONId1 returns the union data inside the FeatureGeoJSON_Id as a FeatureGeoJSONId1
func (t FeatureGeoJSON_Id) AsFeatureGeoJSONId1() (FeatureGeoJSONId1, error) {
	var body FeatureGeoJSONId1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFeatureGeoJSONId1 overwrites any union data inside the FeatureGeoJSON_Id as the provided FeatureGeoJSONId1
func (t *FeatureGeoJSON_Id) FromFeatureGeoJSONId1(v FeatureGeoJSONId1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFeatureGeoJSONId1 performs a merge with any union data inside the FeatureGeoJSON_Id, using the provided FeatureGeoJSONId1
func (t *FeatureGeoJSON_Id) MergeFeatureGeoJSONId1(v FeatureGeoJSONId1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FeatureGeoJSON_Id) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *FeatureGeoJSON_Id) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPointGeoJSON returns the union data inside the GeometryGeoJSON as a PointGeoJSON
func (t GeometryGeoJSON) AsPointGeoJSON() (PointGeoJSON, error) {
	var body PointGeoJSON
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPointGeoJSON overwrites any union data inside the GeometryGeoJSON as the provided PointGeoJSON
func (t *GeometryGeoJSON) FromPointGeoJSON(v PointGeoJSON) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePointGeoJSON performs a merge with any union data inside the GeometryGeoJSON, using the provided PointGeoJSON
func (t *GeometryGeoJSON) MergePointGeoJSON(v PointGeoJSON) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMultipointGeoJSON returns the union data inside the GeometryGeoJSON as a MultipointGeoJSON
func (t GeometryGeoJSON) AsMultipointGeoJSON() (MultipointGeoJSON, error) {
	var body MultipointGeoJSON
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMultipointGeoJSON overwrites any union data inside the GeometryGeoJSON as the provided MultipointGeoJSON
func (t *GeometryGeoJSON) FromMultipointGeoJSON(v MultipointGeoJSON) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMultipointGeoJSON performs a merge with any union data inside the GeometryGeoJSON, using the provided MultipointGeoJSON
func (t *GeometryGeoJSON) MergeMultipointGeoJSON(v MultipointGeoJSON) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLinestringGeoJSON returns the union data inside the GeometryGeoJSON as a LinestringGeoJSON
func (t GeometryGeoJSON) AsLinestringGeoJSON() (LinestringGeoJSON, error) {
	var body LinestringGeoJSON
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLinestringGeoJSON overwrites any union data inside the GeometryGeoJSON as the provided LinestringGeoJSON
func (t *GeometryGeoJSON) FromLinestringGeoJSON(v LinestringGeoJSON) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLinestringGeoJSON performs a merge with any union data inside the GeometryGeoJSON, using the provided LinestringGeoJSON
func (t *GeometryGeoJSON) MergeLinestringGeoJSON(v LinestringGeoJSON) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMultilinestringGeoJSON returns the union data inside the GeometryGeoJSON as a MultilinestringGeoJSON
func (t GeometryGeoJSON) AsMultilinestringGeoJSON() (MultilinestringGeoJSON, error) {
	var body MultilinestringGeoJSON
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMultilinestringGeoJSON overwrites any union data inside the GeometryGeoJSON as the provided MultilinestringGeoJSON
func (t *GeometryGeoJSON) FromMultilinestringGeoJSON(v MultilinestringGeoJSON) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMultilinestringGeoJSON performs a merge with any union data inside the GeometryGeoJSON, using the provided MultilinestringGeoJSON
func (t *GeometryGeoJSON) MergeMultilinestringGeoJSON(v MultilinestringGeoJSON) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPolygonGeoJSON returns the union data inside the GeometryGeoJSON as a PolygonGeoJSON
func (t GeometryGeoJSON) AsPolygonGeoJSON() (PolygonGeoJSON, error) {
	var body PolygonGeoJSON
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPolygonGeoJSON overwrites any union data inside the GeometryGeoJSON as the provided PolygonGeoJSON
func (t *GeometryGeoJSON) FromPolygonGeoJSON(v PolygonGeoJSON) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePolygonGeoJSON performs a merge with any union data inside the GeometryGeoJSON, using the provided PolygonGeoJSON
func (t *GeometryGeoJSON) MergePolygonGeoJSON(v PolygonGeoJSON) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMultipolygonGeoJSON returns the union data inside the GeometryGeoJSON as a MultipolygonGeoJSON
func (t GeometryGeoJSON) AsMultipolygonGeoJSON() (MultipolygonGeoJSON, error) {
	var body MultipolygonGeoJSON
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMultipolygonGeoJSON overwrites any union data inside the GeometryGeoJSON as the provided MultipolygonGeoJSON
func (t *GeometryGeoJSON) FromMultipolygonGeoJSON(v MultipolygonGeoJSON) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMultipolygonGeoJSON performs a merge with any union data inside the GeometryGeoJSON, using the provided MultipolygonGeoJSON
func (t *GeometryGeoJSON) MergeMultipolygonGeoJSON(v MultipolygonGeoJSON) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGeometrycollectionGeoJSON returns the union data inside the GeometryGeoJSON as a GeometrycollectionGeoJSON
func (t GeometryGeoJSON) AsGeometrycollectionGeoJSON() (GeometrycollectionGeoJSON, error) {
	var body GeometrycollectionGeoJSON
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGeometrycollectionGeoJSON overwrites any union data inside the GeometryGeoJSON as the provided GeometrycollectionGeoJSON
func (t *GeometryGeoJSON) FromGeometrycollectionGeoJSON(v GeometrycollectionGeoJSON) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGeometrycollectionGeoJSON performs a merge with any union data inside the GeometryGeoJSON, using the provided GeometrycollectionGeoJSON
func (t *GeometryGeoJSON) MergeGeometrycollectionGeoJSON(v GeometrycollectionGeoJSON) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t GeometryGeoJSON) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *GeometryGeoJSON) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
